use zomatodb;
select * from zomato_orders;
select * from zomato_restaurants;

# task 2 

WITH CTE AS (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY order_id, restaurant_id, customer_id, order_date, order_time,
                            delivery_time, total_cost, item_count, payment_method, customer_rating
               ORDER BY order_id
           ) AS rn
    FROM Zomato_orders
)
SELECT * FROM CTE WHERE rn > 1;

WITH CTE AS (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY restaurant_id, restaurant_name, city, area, cuisine,
                            avg_rating, total_ratings, price_range, delivery_available
               ORDER BY restaurant_id
           ) AS rn
    FROM Zomato_restaurants
    )
    SELECT * FROM CTE WHERE rn > 1;
    
    
# to replace null in restaurants  table
SELECT 
    restaurant_id,
ifnull(restaurant_name, 'Unknown') AS restaurant_name,
ifnull(city, 'Not Provided') AS city,
ifnull(avg_rating, 0) AS avg_rating,
ifnull(delivery_available, 'No') AS delivery_available
FROM Zomato_restaurants;


# to replace null in orders table

Select order_id,
Ifnull(payment_method, 'Cash') AS payment_method,
ifnull(customer_rating, 0) AS customer_rating
from zomato_orders;


# to find the count of cities

 SELECT city, COUNT(*) AS restaurant_count
FROM zomato_restaurants
GROUP BY city
ORDER BY restaurant_count DESC;


    #  	Find the top 5 cities with the highest number of orders.
  
SELECT r.city, COUNT(o.order_id) AS total_orders
FROM Zomato_orders as  o
JOIN Zomato_restaurants as r
    ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY total_orders desc
limit 5 ;

 # 	Calculate the total revenue generated by each restaurant.

SELECT r.restaurant_id,
       r.restaurant_name,
      Round( SUM(o.total_cost)) AS total_revenue
FROM Zomato_orders o
JOIN Zomato_restaurants r
    ON o.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name
ORDER BY total_revenue DESC;
  
# total revenue city wise (extra task ) 

SELECT r.city,
       ROUND(SUM(o.total_cost), 2) AS total_revenue
FROM Zomato_orders o
JOIN Zomato_restaurants r
    ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY total_revenue DESC;









